#!/usr/bin/env bash
# Opens (or updates) the weekly review issue with the governance checklist (notes §10).
set -euo pipefail
week=$(date -u +%G-W%V)
title="Weekly review $week"
body=$(cat <<MD
Weekly review checklist (notes Section 10: documented review, not automatic demotion).

- [ ] Venues reviewed? \`config/venues.yaml\` \`reviewed_on\` updated; any withdrawal halts, licensing changes, proof-of-reserves updates.
- [ ] Events reviewed? \`config/events.yaml\`: upgrades, listings, regulatory dates for the next four weeks, each with a source URL.
- [ ] Thresholds unchanged? \`config/thresholds.yaml\` \`calibrated_on\` untouched; if a change is proposed, attach the written case that the mechanism changed.
- [ ] Systemic exposures list still current (stablecoins, lending protocols, bridges, collateral assets)?
- [ ] Sector map reviewed (quarterly) — \`config/universe.yaml\` sector_map.reviewed_on.
- [ ] Rule owners presented trailing hit rates (methods page) and argued for retention / modification / removal; decision recorded in \`docs/changelog.md\`.
- [ ] Data-source status page: any table stale or unavailable for more than a week?

Generated by the weekly workflow on $(date -u +%Y-%m-%d).
MD
)
existing=$(gh issue list --state open --search "\"$title\" in:title" --json number -q '.[0].number' || true)
if [ -n "$existing" ]; then
  echo "issue #$existing already open"
else
  gh issue create --title "$title" --body "$body" --label review || gh issue create --title "$title" --body "$body"
fi
